### PR TITLE
Add layouts page

### PR DESCRIPTION
**Pull request by edfloreshz**
Layouts are here! 🎉  will you create custom panel arrangements and save them for later use. 

Tweaks comes with 4 standard layouts: COSMIC, macOS, Windows, and Ubuntu. More layouts are on the way.

image

Thanks to @ryanabx for implementing the logic behind this.

### CODE REVIEW

**Review by ryanabx — APPROVED** [review]
Let's ship it! The UI looks great, and from my testing it works!

**Comment by edfloreshz** [comment]
Why are you not in cosmic-utils? I'll send you an invite

**Comment by ryanabx** [comment]
Is CI broken? If that's expected I can go ahead and merge

**Comment by edfloreshz** [comment]
Yeah it's broken, I'll send a fix after merging.

**Comment by edfloreshz** [comment]
Thanks @ryanabx!

**Pull request merged**
