### PR TITLE
chore(dev): add nix development shell and package

### PR DESCRIPTION
**Pull request by HeitorAugustoLN**
- Updated .gitignore to include .direnv and nix package build result
- Added .envrc for nix-direnv to automatically setup development environment when using nix

### CODE REVIEW

**Comment by edfloreshz** [comment]
Thanks for submitting this, is it possible to have these files inside a `nix` directory? 

I'd like to avoid having more files In the root of the project.

**Comment by HeitorAugustoLN** [comment]
> Thanks for submitting this, is it possible to have these files inside a `nix` directory?
> 
> I'd like to avoid having more files In the root of the project.

All of them would be really inconvenient for those who are developing using nix, specially .envrc and flake.nix (includes lockfile). But I could remove shell.nix (backwards compatibility only) and move the package to the `nix` directory

**Comment by edfloreshz** [comment]
If they need to be in the root directory we can merge it that way, I was just wondering.

If you’d like to revert the last commit we can merge it how it was originally.

**Comment by HeitorAugustoLN** [comment]
> If they need to be in the root directory we can merge it that way, I was just wondering.
> 
> If you’d like to revert the last commit we can merge it how it was originally.

It is better that way, because it will be backwards-compatible with previous versions of nix that didn't have flakes or for people that still aren't using flakes. `shell.nix` is for entering `nix-shell` and `default.nix` is for `nix-build` to build the package

**Pull request merged**
